version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - HIVEMQ_HOST=${HIVEMQ_HOST}
      - HIVEMQ_USERNAME=${HIVEMQ_USERNAME}
      - HIVEMQ_PASSWORD=${HIVEMQ_PASSWORD}
      - PORT=3001
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
